//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::EventType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "events")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_id: String,
    pub mission_id: String,
    pub event_type: EventType,
    #[sea_orm(column_type = "Text", nullable)]
    pub message: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::missions::Entity",
        from = "Column::MissionId",
        to = "super::missions::Column::MissionId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Missions,
}

impl Related<super::missions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Missions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
