//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{ Deserialize, Serialize };

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_type")]
pub enum EventType {
    #[sea_orm(string_value = "takeoff")]
    Takeoff,
    #[sea_orm(string_value = "landing")]
    Landing,
    #[sea_orm(string_value = "battery_low")]
    BatteryLow,
    #[sea_orm(string_value = "obstacle_detected")]
    ObstacleDetected,
    #[sea_orm(string_value = "return")]
    Return,
    #[sea_orm(string_value = "error")]
    Error,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "log_type")]
pub enum LogType {
    #[sea_orm(string_value = "INFO")]
    Info,
    #[sea_orm(string_value = "WARN")]
    Warn,
    #[sea_orm(string_value = "ERROR")]
    Error,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "role")]
pub enum Role {
    #[sea_orm(string_value = "superadmin")]
    Superadmin,
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "user")]
    User,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "status")]
pub enum Status {
    #[sea_orm(string_value = "idle")]
    Idle,
    #[sea_orm(string_value = "working")]
    Working,
    #[sea_orm(string_value = "returning")]
    Returning,
    #[sea_orm(string_value = "completed")]
    Completed,
    #[sea_orm(string_value = "error")]
    Error,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "incident_status")]
pub enum IncidentStatus {
    #[sea_orm(string_value = "open")]
    Open,
    #[sea_orm(string_value = "processing")]
    Processing,
    #[sea_orm(string_value = "closed")]
    Closed,
}
