//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::Role;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: String,
    pub name: String,
    pub password: String,
    pub role: Role,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::incidents::Entity")]
    Incidents,
    #[sea_orm(has_many = "super::missions::Entity")]
    Missions,
}

impl Related<super::incidents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Incidents.def()
    }
}

impl Related<super::missions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Missions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
